# STATEWISE RULING PARTY

In [20]:
# https://en.wikipedia.org/wiki/List_of_current_Indian_chief_ministers

#### Importing required libraries

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import os
import datetime
import statistics as stat

#### Reading: STATEWISE_RULING_PARTY.csv

In [22]:
ruling_party = pd.read_csv('Raw Datasets/Supportive Datasets/STATEWISE_RULING_PARTY.CSV')

ruling_party.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   29 non-null     object
 1   2001    26 non-null     object
 2   2004    27 non-null     object
 3   2009    29 non-null     object
 4   2014    29 non-null     object
 5   2019    29 non-null     object
 6   2024    29 non-null     object
dtypes: object(7)
memory usage: 1.7+ KB

#### Data Cleaning

In [23]:
ruling_party.fillna("Unknown", inplace=True)

In [24]:
ruling_party.head()

,State,2001,2004,2009,2014,2019,2024
0,Andhra Pradesh,TDP,INC,INC,TDP,YSRCP,TDP
1,Arunachal Pradesh,INC,INC,INC,BJP,BJP,BJP
2,Assam,AGP,INC,INC,BJP,BJP,BJP
3,Bihar,RJD,INC-RJD,BJP-JD(U),BJP-JD(U),NDA (JD(U)),NDA (JD(U))
4,Chhattisgarh,Unknown,INC,INC,BJP,INC,BJP

#### Reshape for Analysis

In [25]:
ruling_party_expanded = ruling_party.melt(
    id_vars=['State'], 
    var_name='Year', 
    value_name='Ruling_Party'
)

In [26]:
ruling_party_expanded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         174 non-null    object
 1   Year          174 non-null    object
 2   Ruling_Party  174 non-null    object
dtypes: object(3)
memory usage: 4.2+ KB

In [27]:
ruling_party_expanded.head(10)

               State  Year Ruling_Party
0     Andhra Pradesh  2001          TDP
1  Arunachal Pradesh  2001          INC
2              Assam  2001          AGP
3              Bihar  2001          RJD
4       Chhattisgarh  2001      Unknown
5              Delhi  2001          INC
6                Goa  2001          INC
7            Gujarat  2001          INC
8            Haryana  2001         INLD
9   Himachal Pradesh  2001          INC

# COMMUNITYWISE POPULATION CENSUS 2011

In [28]:
# https://censusindia.gov.in/nada/index.php/catalog/11361

In [29]:
comm_wise_population = pd.read_csv('Raw Datasets/Supportive Datasets/COMMUNITYWISE POPULATION - DDW00C-01 MDDS converted.csv')

comm_wise_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   table_name          108 non-null    object
 1   state_code          108 non-null    int64
 2   distt_code          108 non-null    int64
 3   tehsil_code         108 non-null    int64
 4   town_code           108 non-null    int64
 5   area_name           108 non-null    object
 6   total_rural_urban   108 non-null    object
 7   total_persons       108 non-null    int64
 8   total_males         108 non-null    int64
 9   total_females       108 non-null    int64
 10  total_hindu         108 non-null    int64
 11  hindu_male          108 non-null    int64
 12  hindu_female        108 non-null    int64
 13  total_muslim        108 non-null    int64
 14  muslim_male         108 non-null    int64
 15  muslim_female       108 non-null    int64
 16  total_christian     108 non-null    int64
 17  christian_male      108 non-null    int64
 18  christian_female    108 non-null    int64
 19  total_sikh          108 non-null    int64
 20  sikh_male           108 non-null    int64
 21  sikh_female         108 non-null    int64
 22  total_buddhist      108 non-null    int64
 23  buddhist_male       108 non-null    int64
 24  buddhist_female     108 non-null    int64
 25  total_jain          108 non-null    int64
 26  jain_male           108 non-null    int64
 27  jain_female         108 non-null    int64
 28  total_others        108 non-null    int64
 29  other_male          108 non-null    int64
 30  other_female        108 non-null    int64
 31  no_religion_total   108 non-null    int64
 32  no_religion_male    108 non-null    int64
 33  no_religion_female  108 non-null    int64
dtypes: int64(31), object(3)
memory usage: 28.8+ KB

### Filteration

In [30]:
# keeping total columns
state_total = comm_wise_population[
    comm_wise_population['total_rural_urban'].str.strip().str.lower() == 'total'
].copy()

state_total = state_total[
    [
        'state_code',
        'area_name',
        'total_persons',
        'total_hindu',
        'total_muslim',
        'total_christian',
        'total_sikh',
        'total_buddhist',
        'total_jain',
        'total_others',
        'no_religion_total'
    ]
]


state_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36 entries, 0 to 105
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state_code         36 non-null     int64
 1   area_name          36 non-null     object
 2   total_persons      36 non-null     int64
 3   total_hindu        36 non-null     int64
 4   total_muslim       36 non-null     int64
 5   total_christian    36 non-null     int64
 6   total_sikh         36 non-null     int64
 7   total_buddhist     36 non-null     int64
 8   total_jain         36 non-null     int64
 9   total_others       36 non-null     int64
 10  no_religion_total  36 non-null     int64
dtypes: int64(10), object(1)
memory usage: 3.4+ KB

#### % of population

In [31]:
religion_cols = [
    'total_hindu',
    'total_muslim',
    'total_christian',
    'total_sikh',
    'total_buddhist',
    'total_jain',
    'total_others',
    'no_religion_total'
]

for col in religion_cols:
    state_total[col.replace('total_', '') + '_percent'] = (
        state_total[col] / state_total['total_persons'] * 100
    )

state_total.head()

,state_code,area_name,total_persons,total_hindu,total_muslim,total_christian,total_sikh,total_buddhist,total_jain,total_others,no_religion_total,hindu_percent,muslim_percent,christian_percent,sikh_percent,buddhist_percent,jain_percent,others_percent,no_religion_total_percent
0,0,INDIA,1210854977,966257353,172245158,27819588,20833116,8442972,4451753,7937734,2867303,79.799594,14.225086,2.297516,1.720529,0.697274,0.367654,0.655548,0.236800
3,1,State - JAMMU & KASHMIR,12541302,3566674,8567485,35631,234848,112584,2490,1508,20082,28.439424,68.314159,0.284109,1.872597,0.897706,0.019854,0.012024,0.160127
6,2,State - HIMACHAL PRADESH,6864602,6532765,149881,12646,79896,78659,1805,856,8094,95.165969,2.183390,0.184220,1.163884,1.145864,0.026294,0.012470,0.117909
9,3,State - PUNJAB,27743338,10678138,535489,348230,16004754,33237,45040,10886,87564,38.489017,1.930153,1.255184,57.688639,0.119802,0.162345,0.039238,0.315622
12,4,State - CHANDIGARH,1055450,852574,51447,8720,138329,1160,1960,246,1014,80.778246,4.874414,0.826188,13.106163,0.109906,0.185703,0.023308,0.096073

In [32]:
# dropping row count
state_comm_percent = state_total.drop(columns=religion_cols)

In [33]:
state_comm_percent.head()

,state_code,area_name,total_persons,hindu_percent,muslim_percent,christian_percent,sikh_percent,buddhist_percent,jain_percent,others_percent,no_religion_total_percent
0,0,INDIA,1210854977,79.799594,14.225086,2.297516,1.720529,0.697274,0.367654,0.655548,0.236800
3,1,State - JAMMU & KASHMIR,12541302,28.439424,68.314159,0.284109,1.872597,0.897706,0.019854,0.012024,0.160127
6,2,State - HIMACHAL PRADESH,6864602,95.165969,2.183390,0.184220,1.163884,1.145864,0.026294,0.012470,0.117909
9,3,State - PUNJAB,27743338,38.489017,1.930153,1.255184,57.688639,0.119802,0.162345,0.039238,0.315622
12,4,State - CHANDIGARH,1055450,80.778246,4.874414,0.826188,13.106163,0.109906,0.185703,0.023308,0.096073

### Export

In [34]:
state_comm_percent.to_csv("FilteredData/census_2011_religionwise_population.csv", index=False)

In [35]:
ruling_party_expanded.to_csv('FilteredData/ruling_party_expanded.csv', index=False)